### ISSUE TITLE
Custom operator class generates invalid output

### ISSUE THREAD

**Issue by gorkaio** [K-Phoen/RulerZBundle#5]
I'm trying to implement RulerZBundle in a Symfony+Doctrine project, but I'm facing some difficulties trying to define custom operators. Following the simple 'LIKE' example, the operator is defined as follows:

``` php

namespace MyProject\Infrastructure\Persistence\Doctrine\Operator;

class Like
{
    public function __invoke($a, $b)
    {
        return sprintf('%s LIKE %s', $a, $b);
    }
}
```

The operator is declared as service in `services.yml` and tagged as stated in the docs:

``` yaml
  operator.doctrine.like:
    class: MyProject\Infrastructure\Persistence\Doctrine\Operator\Like
    tags:
        - { name: rulerz.operator, executor: rulerz.executor.doctrine, operator: like }
```

The Specification using this custom operator:

``` php
namespace MyProject\Domain\Query\Item;

use MyProject\Domain\Query\Specification;

class HasNameLike implements Specification
{
    /**
     * @var
     */
    private $name;

    /**
     * HasNameLike constructor.
     * @param $name
     */
    public function __construct($name)
    {
        $this->name = $name;
    }

    /**
     * @return string
     */
    public function getRule()
    {
        return 'name like :name';
    }

    /**
     * @return array
     */
    public function getParameters()
    {
        return ['name' => $this->name];
    }
}
```

However, trying to run this spec through `applyFilterSpec` it generates the following Executor cache, that contains a Syntax Error:

``` php
<?php
namespace RulerZ\Compiled\Executor;

use RulerZ\Executor\Executor;

class Executor_a5fb7577 implements Executor
{
        use \RulerZ\Executor\DoctrineQueryBuilder\FilterTrait;
    use \RulerZ\Executor\DoctrineQueryBuilder\AutoJoinTrait;
    use \RulerZ\Executor\Polyfill\FilterBasedSatisfaction;

    private $detectedJoins = array (
);


    // name like :name
    protected function execute($target, array $operators, array $parameters)
    {
        return "call_user_func($operators["like"], @@_ROOT_ALIAS_@@.name, :name)";
    }
}
```

Am I correctly defining the custom operator class or is there anything else missing? I've been loking through the documentation for an example, but I have not found any.

**Comment by K-Phoen** [comment]
Your service definition should probably be like that:

``` yaml
  operator.doctrine.like:
    class: MyProject\Infrastructure\Persistence\Doctrine\Operator\Like
    tags:
        - { name: rulerz.operator, executor: rulerz.executor.doctrine, operator: like, inline: true }
```

Notice the `inline: true` attribute.

The documentation isn't as up-to-date as it should be… sorry for that.
